package constants

const MAX_VIEWPORT_ZOOM = 2400
const MIN_VIEWPORT_ZOOM = -2400
const AUTO_PADDING = 20

const CAMERA_FOCUS_BOX_LINEAR = "FOCUS_BOX_LINEAR"
const CAMERA_FOCUS_BOX_LERP = "FOCUS_BOX_LERP"
const CAMERA_FOCUS_POINT_BASIC = "FOCUS_POINT_BASIC"
